[workspace]

members = ["rox", "tools", "macros"]
version = "0.1.0"
edition = "2021"

[workspace.package]
version = "0.1.0"
authors = ["lefoun"]
description = "A programming language based on the Crafting Interpreters book"